### ISSUE TITLE
404 message when visiting 127.0.0.1:5000 

### ISSUE THREAD

**Issue by jfonte** [LandonFuhr/shopify-reviews-scraper#2]
Hi there. When visiting the running address 127.0.0.1:5000, I am getting a 404 message. Is this normal or there some other address I need to head to to begin the scraping? Cheers.

![image](https://user-images.githubusercontent.com/3999437/160475259-828697b8-1941-4751-9cbe-3251b37695f9.png)

**Comment by LandonFuhr** [comment]
Hey, you can try `/count?app={your_app_name}` to get the review counts (overall rating and breakdown by stars). Or try `/messages?app={your_app_name}&page=1` to get a list of reviews left by customers, including the messages.

E.g. `http://localhost:5000/count?app=aftersell` for the app listing https://apps.shopify.com/aftersell

**Comment by jfonte** [comment]
Thank you! _/count?app={your_app_name}_ worked for me. Q: what parameters can I use to scrape reviews from all pages?

**Comment by LandonFuhr** [comment]
Currently there is no way to scrape all reviews. Some apps have 10K+ reviews which would make it incredibly slow since the server would have to go through each page individually to get all reviews. You could iterate through `/messages?app={your_app_name}&page=1 ` and then `page=2`, `page=3` etc. until it returns nothing, meaning you've gone through all of the pages.
